/// Generated by rustemo. Do not edit manually!
use regex::Regex;
use num_enum::TryFromPrimitive;
use std::{convert::TryFrom, fmt::Debug};
use rustemo_rt::lexer::{Lexer, Token};
use rustemo_rt::parser::Parser;
use rustemo_rt::builder::Builder;
use rustemo_rt::Result;
use rustemo_rt::lr::lexer::{
    LRStringLexer, LRContext, LexerDefinition, RecognizerIterator,
};
use rustemo_rt::lr::builder::LRBuilder;
use rustemo_rt::lr::parser::{LRParser, ParserDefinition};
use rustemo_rt::lr::parser::Action::{self, Shift, Reduce, Accept, Error};
use rustemo_rt::index::{StateIndex, TermIndex, NonTermIndex, ProdIndex};
use rustemo_rt::grammar::{TerminalInfo, TerminalInfos, TerminalsState};
use rustemo_rt::debug::{log, logn};
use super::zero_or_more_actions;
const TERMINAL_NO: usize = 4usize;
const NONTERMINAL_NO: usize = 6usize;
const STATE_NO: usize = 6usize;
const MAX_ACTIONS: usize = 2usize;
#[derive(Debug, Copy, Clone, TryFromPrimitive)]
#[repr(usize)]
pub enum TermKind {
    STOP = 0usize,
    TA = 1usize,
    TB = 2usize,
    TC = 3usize,
}
#[derive(Debug)]
pub enum Symbol {
    Terminal(Terminal),
    NonTerminal(NonTerminal),
}
#[derive(Debug)]
pub enum Terminal {
    STOP,
    TA,
    TB,
    TC,
}
#[derive(Debug)]
pub enum NonTerminal {
    A(zero_or_more_actions::A),
    TC1(zero_or_more_actions::TC1),
    TC0(zero_or_more_actions::TC0),
    B(zero_or_more_actions::B),
}
#[derive(Copy, Clone, TryFromPrimitive)]
#[repr(usize)]
pub enum ProdKind {
    AP1 = 1usize,
    TC1P1 = 2usize,
    TC1P2 = 3usize,
    TC0P1 = 4usize,
    TC0P2 = 5usize,
    BP1 = 6usize,
    BP2 = 7usize,
}
pub struct ZeroOrMoreParserDefinition {
    actions: [[Action; TERMINAL_NO]; STATE_NO],
    gotos: [[Option<StateIndex>; NONTERMINAL_NO]; STATE_NO],
}
pub(crate) static PARSER_DEFINITION: ZeroOrMoreParserDefinition = ZeroOrMoreParserDefinition {
    actions: [
        [Error, Error, Error, Shift(StateIndex(1usize), TermIndex(3usize))],
        [
            Error,
            Error,
            Shift(StateIndex(3usize), TermIndex(2usize)),
            Reduce(ProdIndex(7usize), 0usize, NonTermIndex(5usize), "<?>"),
        ],
        [Accept, Error, Error, Error],
        [
            Error,
            Error,
            Error,
            Reduce(ProdIndex(6usize), 1usize, NonTermIndex(5usize), "<?>"),
        ],
        [Error, Error, Error, Shift(StateIndex(5usize), TermIndex(3usize))],
        [
            Reduce(ProdIndex(1usize), 3usize, NonTermIndex(2usize), "<?>"),
            Error,
            Error,
            Error,
        ],
    ],
    gotos: [
        [None, None, Some(StateIndex(2usize)), None, None, None],
        [None, None, None, None, None, Some(StateIndex(4usize))],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
        [None, None, None, None, None, None],
    ],
};
impl ParserDefinition for ZeroOrMoreParserDefinition {
    fn action(&self, state_index: StateIndex, term_index: TermIndex) -> Action {
        PARSER_DEFINITION.actions[state_index.0][term_index.0]
    }
    fn goto(&self, state_index: StateIndex, nonterm_index: NonTermIndex) -> StateIndex {
        PARSER_DEFINITION.gotos[state_index.0][nonterm_index.0].unwrap()
    }
}
pub struct ZeroOrMoreParser(LRParser<ZeroOrMoreParserDefinition>);
impl<I, L, B> Parser<I, LRContext<I>, L, B> for ZeroOrMoreParser
where
    I: Debug,
    L: Lexer<I, LRContext<I>>,
    B: LRBuilder<I>,
{
    fn parse(
        &mut self,
        context: LRContext<I>,
        lexer: L,
        builder: B,
    ) -> Result<B::Output> {
        ZeroOrMoreParser::default().0.parse(context, lexer, builder)
    }
}
#[allow(dead_code)]
impl ZeroOrMoreParser {
    pub fn parse_str<'i>(
        input: &'i str,
    ) -> Result<<ZeroOrMoreBuilder as Builder>::Output> {
        let context = LRContext::new("<str>".to_string(), input);
        let lexer = LRStringLexer::new(&LEXER_DEFINITION);
        let builder = ZeroOrMoreBuilder::new();
        ZeroOrMoreParser::default().0.parse(context, lexer, builder)
    }
}
impl Default for ZeroOrMoreParser {
    fn default() -> Self {
        Self(LRParser::new(&PARSER_DEFINITION))
    }
}
pub struct ZeroOrMoreLexerDefinition {
    terminals: TerminalInfos<TERMINAL_NO>,
    terminals_for_state: TerminalsState<MAX_ACTIONS, STATE_NO>,
    recognizers: [fn(&str) -> Option<&str>; TERMINAL_NO],
}
pub(crate) static LEXER_DEFINITION: ZeroOrMoreLexerDefinition = ZeroOrMoreLexerDefinition {
    terminals: [
        TerminalInfo {
            id: TermIndex(0usize),
            name: "STOP",
            location: None,
        },
        TerminalInfo {
            id: TermIndex(1usize),
            name: "TA",
            location: None,
        },
        TerminalInfo {
            id: TermIndex(2usize),
            name: "TB",
            location: None,
        },
        TerminalInfo {
            id: TermIndex(3usize),
            name: "TC",
            location: None,
        },
    ],
    terminals_for_state: [
        [Some(3usize), None],
        [Some(2usize), Some(3usize)],
        [Some(0usize), None],
        [Some(3usize), None],
        [Some(3usize), None],
        [Some(0usize), None],
    ],
    recognizers: [
        |input: &str| {
            logn!("Recognizing <STOP> -- ");
            if input.len() == 0 {
                log!("recognized");
                Some("")
            } else {
                log!("not recognized");
                None
            }
        },
        |input: &str| {
            logn!("Recognizing <{}> -- ", "TA");
            if input.starts_with("a") {
                log!("recognized");
                Some("a")
            } else {
                log!("not recognized");
                None
            }
        },
        |input: &str| {
            logn!("Recognizing <{}> -- ", "TB");
            if input.starts_with("b") {
                log!("recognized");
                Some("b")
            } else {
                log!("not recognized");
                None
            }
        },
        |input: &str| {
            logn!("Recognizing <{}> -- ", "TC");
            if input.starts_with("c") {
                log!("recognized");
                Some("c")
            } else {
                log!("not recognized");
                None
            }
        },
    ],
};
impl LexerDefinition for ZeroOrMoreLexerDefinition {
    type Recognizer = for<'i> fn(&'i str) -> Option<&'i str>;
    fn recognizers(
        &self,
        state_index: StateIndex,
    ) -> RecognizerIterator<Self::Recognizer> {
        RecognizerIterator {
            terminals: &LEXER_DEFINITION.terminals,
            terminals_for_state: &LEXER_DEFINITION
                .terminals_for_state[state_index.0][..],
            recognizers: &LEXER_DEFINITION.recognizers,
            index: 0,
        }
    }
}
pub struct ZeroOrMoreBuilder {
    res_stack: Vec<Symbol>,
}
impl Builder for ZeroOrMoreBuilder {
    type Output = zero_or_more_actions::A;
    fn new() -> Self {
        Self { res_stack: vec![] }
    }
    fn get_result(&mut self) -> Result<Self::Output> {
        match self.res_stack.pop().unwrap() {
            Symbol::NonTerminal(NonTerminal::A(r)) => Ok(r),
            _ => panic!("Invalid result on the parsing stack!"),
        }
    }
}
impl<'i> LRBuilder<&'i str> for ZeroOrMoreBuilder {
    #![allow(unused_variables)]
    fn shift_action(&mut self, term_idx: TermIndex, token: Token<&'i str>) {
        let termval = match TermKind::try_from(term_idx.0).unwrap() {
            TermKind::STOP => Terminal::STOP,
            TermKind::TA => Terminal::TA,
            TermKind::TB => Terminal::TB,
            TermKind::TC => Terminal::TC,
        };
        self.res_stack.push(Symbol::Terminal(termval));
    }
    fn reduce_action(
        &mut self,
        prod_kind: ProdIndex,
        _prod_len: usize,
        _prod_str: &'static str,
    ) {
        let prod = match ProdKind::try_from(prod_kind.0).unwrap() {
            ProdKind::AP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 3usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap(), i.next().unwrap()) {
                    (_, Symbol::NonTerminal(NonTerminal::B(p0)), _) => {
                        NonTerminal::A(zero_or_more_actions::a_v1(p0))
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::TC1P1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 2usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap()) {
                    (Symbol::NonTerminal(NonTerminal::TC1(p0)), _) => {
                        NonTerminal::TC1(zero_or_more_actions::tc1_v1(p0))
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::TC1P2 => {
                let _ = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                NonTerminal::TC1(zero_or_more_actions::tc1_v2())
            }
            ProdKind::TC0P1 => {
                let _ = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                NonTerminal::TC0(zero_or_more_actions::tc0_v1())
            }
            ProdKind::TC0P2 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::NonTerminal(NonTerminal::EMPTY(p0)) => {
                        NonTerminal::TC0(zero_or_more_actions::tc0_v2(p0))
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::BP1 => {
                let _ = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                NonTerminal::B(zero_or_more_actions::b_v1())
            }
            ProdKind::BP2 => NonTerminal::B(zero_or_more_actions::b_empty()),
        };
        self.res_stack.push(Symbol::NonTerminal(prod));
    }
}
