/// Generated by rustemo. Do not edit manually!
use regex::Regex;
use std::fmt::Debug;
use rustemo::lexer::{self, Token, AsStr};
use rustemo::parser::Parser;
use rustemo::builder::Builder;
use rustemo::Result;
use rustemo::lr::lexer::{LRStringLexer, LexerDefinition, RecognizerIterator};
use rustemo::lr::builder::LRBuilder;
use rustemo::lr::parser::{LRParser, ParserDefinition};
use rustemo::lr::parser::Action::{self, Shift, Reduce, Accept, Error};
use rustemo::index::{StateIndex, TermIndex, NonTermIndex, ProdIndex};
use rustemo::grammar::TerminalsState;
use rustemo::debug::{log, logn};
const TERMINAL_NO: usize = 3usize;
const NONTERMINAL_NO: usize = 5usize;
const STATE_NO: usize = 7usize;
#[allow(dead_code)]
const MAX_ACTIONS: usize = 2usize;
use super::output_dir_actions;
pub type Input = str;
pub type Context<'i> = lexer::Context<'i, Input, StateIndex>;
use lazy_static::lazy_static;
lazy_static! {
    static ref REGEX_NUM : Regex = Regex::new(concat!("^", "\\d+")).unwrap();
}
#[allow(clippy::upper_case_acronyms)]
#[derive(Debug, Clone, Copy)]
pub enum TokenKind {
    Tb,
    Num,
}
impl AsStr for TokenKind {
    #[allow(dead_code)]
    fn as_str(&self) -> &'static str {
        match self {
            TokenKind::Tb => "Tb",
            TokenKind::Num => "Num",
        }
    }
}
impl From<TermIndex> for TokenKind {
    fn from(term_index: TermIndex) -> Self {
        match term_index.0 {
            1usize => TokenKind::Tb,
            2usize => TokenKind::Num,
            _ => unreachable!(),
        }
    }
}
impl From<TokenKind> for TermIndex {
    fn from(token_kind: TokenKind) -> Self {
        match token_kind {
            TokenKind::Tb => TermIndex(1usize),
            TokenKind::Num => TermIndex(2usize),
        }
    }
}
#[allow(clippy::enum_variant_names)]
#[derive(Clone, Copy)]
pub enum ProdKind {
    AP1,
    B1P1,
    B1P2,
    BP1,
}
impl AsStr for ProdKind {
    #[allow(dead_code)]
    fn as_str(&self) -> &'static str {
        match self {
            ProdKind::AP1 => "AP1",
            ProdKind::B1P1 => "B1P1",
            ProdKind::B1P2 => "B1P2",
            ProdKind::BP1 => "BP1",
        }
    }
}
impl std::fmt::Display for ProdKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            ProdKind::AP1 => "A: B1 Num",
            ProdKind::B1P1 => "B1: B1 B",
            ProdKind::B1P2 => "B1: B",
            ProdKind::BP1 => "B: Tb",
        };
        write!(f, "{}", name)
    }
}
impl From<ProdIndex> for ProdKind {
    fn from(prod_index: ProdIndex) -> Self {
        match prod_index.0 {
            1usize => ProdKind::AP1,
            2usize => ProdKind::B1P1,
            3usize => ProdKind::B1P2,
            4usize => ProdKind::BP1,
            _ => unreachable!(),
        }
    }
}
#[derive(Debug)]
pub enum Symbol {
    Terminal(Terminal),
    NonTerminal(NonTerminal),
}
#[allow(clippy::upper_case_acronyms)]
#[derive(Debug)]
pub enum Terminal {
    Tb,
    Num(output_dir_actions::Num),
}
#[derive(Debug)]
pub enum NonTerminal {
    A(output_dir_actions::A),
    B1(output_dir_actions::B1),
    B(output_dir_actions::B),
}
pub struct OutputDirParserDefinition {
    actions: [[Action; TERMINAL_NO]; STATE_NO],
    gotos: [[Option<StateIndex>; NONTERMINAL_NO]; STATE_NO],
}
pub(crate) static PARSER_DEFINITION: OutputDirParserDefinition = OutputDirParserDefinition {
    actions: [
        [Error, Shift(StateIndex(1usize)), Error],
        [
            Error,
            Reduce(ProdIndex(4usize), 1usize, NonTermIndex(4usize)),
            Reduce(ProdIndex(4usize), 1usize, NonTermIndex(4usize)),
        ],
        [Accept, Error, Error],
        [Error, Shift(StateIndex(1usize)), Shift(StateIndex(5usize))],
        [
            Error,
            Reduce(ProdIndex(3usize), 1usize, NonTermIndex(3usize)),
            Reduce(ProdIndex(3usize), 1usize, NonTermIndex(3usize)),
        ],
        [Reduce(ProdIndex(1usize), 2usize, NonTermIndex(2usize)), Error, Error],
        [
            Error,
            Reduce(ProdIndex(2usize), 2usize, NonTermIndex(3usize)),
            Reduce(ProdIndex(2usize), 2usize, NonTermIndex(3usize)),
        ],
    ],
    gotos: [
        [
            None,
            None,
            Some(StateIndex(2usize)),
            Some(StateIndex(3usize)),
            Some(StateIndex(4usize)),
        ],
        [None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, Some(StateIndex(6usize))],
        [None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None],
    ],
};
impl ParserDefinition for OutputDirParserDefinition {
    fn action(&self, state_index: StateIndex, term_index: TermIndex) -> Action {
        PARSER_DEFINITION.actions[state_index.0][term_index.0]
    }
    fn goto(&self, state_index: StateIndex, nonterm_index: NonTermIndex) -> StateIndex {
        PARSER_DEFINITION.gotos[state_index.0][nonterm_index.0].unwrap()
    }
}
#[derive(Default)]
pub struct OutputDirParser {
    content: Option<<Input as ToOwned>::Owned>,
}
#[allow(dead_code)]
impl OutputDirParser {
    pub fn new() -> Self {
        Default::default()
    }
    #[allow(clippy::needless_lifetimes)]
    pub fn parse_file<'i, P: AsRef<std::path::Path>>(
        &'i mut self,
        file: P,
    ) -> Result<output_dir_actions::A> {
        self.content = Some(<Input as rustemo::lexer::Input>::read_file(&file)?);
        let mut context = Context::new(
            file.as_ref().to_string_lossy().to_string(),
            self.content.as_ref().unwrap(),
        );
        Self::inner_parse(&mut context)
    }
    #[allow(clippy::needless_lifetimes)]
    pub fn parse<'i>(input: &'i Input) -> Result<output_dir_actions::A> {
        let mut context = Context::new("<str>".to_string(), input);
        Self::inner_parse(&mut context)
    }
    #[allow(clippy::needless_lifetimes)]
    fn inner_parse<'i>(context: &mut Context<'i>) -> Result<output_dir_actions::A> {
        let lexer = LRStringLexer::new(&LEXER_DEFINITION, false, true);
        let mut builder = OutputDirBuilder::new();
        let mut parser = LRParser::new(&PARSER_DEFINITION, StateIndex(0));
        parser.parse(context, &lexer, &mut builder)
    }
}
pub struct OutputDirLexerDefinition {
    terminals_for_state: TerminalsState<MAX_ACTIONS, STATE_NO>,
    recognizers: [fn(&str) -> Option<&str>; TERMINAL_NO],
}
#[allow(clippy::single_char_pattern)]
pub(crate) static LEXER_DEFINITION: OutputDirLexerDefinition = OutputDirLexerDefinition {
    terminals_for_state: [
        [Some(1usize), None],
        [Some(1usize), Some(2usize)],
        [Some(0usize), None],
        [Some(1usize), Some(2usize)],
        [Some(1usize), Some(2usize)],
        [Some(0usize), None],
        [Some(1usize), Some(2usize)],
    ],
    recognizers: [
        |input: &str| {
            logn!("Recognizing <STOP> -- ");
            if input.is_empty() {
                log!("recognized");
                Some("")
            } else {
                log!("not recognized");
                None
            }
        },
        |input: &str| {
            logn!("Recognizing <{}> -- ", "Tb");
            if input.starts_with("b") {
                log!("recognized");
                Some("b")
            } else {
                log!("not recognized");
                None
            }
        },
        |input: &str| {
            logn!("Recognizing <{}> -- ", "Num");
            let match_str = REGEX_NUM.find(input);
            match match_str {
                Some(x) => {
                    let x_str = x.as_str();
                    log!("recognized <{}>", x_str);
                    Some(x_str)
                }
                None => {
                    log!("not recognized");
                    None
                }
            }
        },
    ],
};
impl LexerDefinition for OutputDirLexerDefinition {
    type Recognizer = for<'i> fn(&'i str) -> Option<&'i str>;
    fn recognizers(
        &self,
        state_index: StateIndex,
    ) -> RecognizerIterator<Self::Recognizer> {
        RecognizerIterator {
            terminals_for_state: &LEXER_DEFINITION
                .terminals_for_state[state_index.0][..],
            recognizers: &LEXER_DEFINITION.recognizers,
            index: 0,
        }
    }
}
struct OutputDirBuilder {
    res_stack: Vec<Symbol>,
}
impl Builder for OutputDirBuilder {
    type Output = output_dir_actions::A;
    fn new() -> Self {
        Self { res_stack: vec![] }
    }
    fn get_result(&mut self) -> Self::Output {
        match self.res_stack.pop().unwrap() {
            Symbol::NonTerminal(NonTerminal::A(r)) => r,
            _ => panic!("Invalid result on the parse stack!"),
        }
    }
}
impl<'i> LRBuilder<'i, Input, TokenKind> for OutputDirBuilder {
    #![allow(unused_variables)]
    fn shift_action(
        &mut self,
        context: &mut Context<'i>,
        token: Token<'i, Input, TokenKind>,
    ) {
        let kind = match token.kind {
            lexer::TokenKind::Kind(kind) => kind,
            lexer::TokenKind::STOP => panic!("Cannot shift STOP token!"),
        };
        let val = match kind {
            TokenKind::Tb => Terminal::Tb,
            TokenKind::Num => Terminal::Num(output_dir_actions::num(context, token)),
        };
        self.res_stack.push(Symbol::Terminal(val));
    }
    fn reduce_action(
        &mut self,
        context: &mut Context<'i>,
        prod_idx: ProdIndex,
        _prod_len: usize,
    ) {
        let prod = match ProdKind::from(prod_idx) {
            ProdKind::AP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 2usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap()) {
                    (
                        Symbol::NonTerminal(NonTerminal::B1(p0)),
                        Symbol::Terminal(Terminal::Num(p1)),
                    ) => NonTerminal::A(output_dir_actions::a_c1(context, p0, p1)),
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::B1P1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 2usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap()) {
                    (
                        Symbol::NonTerminal(NonTerminal::B1(p0)),
                        Symbol::NonTerminal(NonTerminal::B(p1)),
                    ) => NonTerminal::B1(output_dir_actions::b1_c1(context, p0, p1)),
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::B1P2 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::NonTerminal(NonTerminal::B(p0)) => {
                        NonTerminal::B1(output_dir_actions::b1_b(context, p0))
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::BP1 => {
                let _ = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                NonTerminal::B(output_dir_actions::b_tb(context))
            }
        };
        self.res_stack.push(Symbol::NonTerminal(prod));
    }
}
